//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.LineRenderer
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/LineRenderer/DOColor")]
    [UnityEngine.RequireComponent(typeof(UnityEngine.LineRenderer))]
    public class DOColor : EasyDOTween.Animation<UnityEngine.LineRenderer>
    {
        
        [UnityEngine.SerializeField()]
        private DG.Tweening.Color2 startValue;
        
        [UnityEngine.SerializeField()]
        private DG.Tweening.Color2 endValue;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.LineRenderer target, float duration)
        {
            return target.DOColor(startValue, endValue, duration);
        }
    }
}
