#if EasyDOTween_UI
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.Text
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/Text/DOText")]
    [UnityEngine.RequireComponent(typeof(UnityEngine.UI.Text))]
    public class DOText : EasyDOTween.Animation<UnityEngine.UI.Text>
    {
        
        [UnityEngine.SerializeField()]
        private string endValue;
        
        [UnityEngine.SerializeField()]
        private bool richTextEnabled = true;
        
        [UnityEngine.SerializeField()]
        private DG.Tweening.ScrambleMode scrambleMode;
        
        [UnityEngine.SerializeField()]
        private string scrambleChars;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.UI.Text target, float duration)
        {
            return target.DOText(endValue, duration, richTextEnabled, scrambleMode, scrambleChars);
        }
    }
}

#endif