//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.TrailRenderer
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/TrailRenderer/DOResize")]
    [UnityEngine.RequireComponent(typeof(UnityEngine.TrailRenderer))]
    public class DOResize : EasyDOTween.Animation<UnityEngine.TrailRenderer>
    {
        
        [UnityEngine.SerializeField()]
        private float toStartWidth;
        
        [UnityEngine.SerializeField()]
        private float toEndWidth;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.TrailRenderer target, float duration)
        {
            return target.DOResize(toStartWidth, toEndWidth, duration);
        }
    }
}
