//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.TrailRenderer
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/TrailRenderer/DOTime")]
    [UnityEngine.RequireComponent(typeof(UnityEngine.TrailRenderer))]
    public class DOTime : EasyDOTween.Animation<UnityEngine.TrailRenderer>
    {
        
        [UnityEngine.SerializeField()]
        private float endValue;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.TrailRenderer target, float duration)
        {
            return target.DOTime(endValue, duration);
        }
    }
}
