#if EasyDOTween_Audio
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.AudioSource
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/AudioSource/DOPitch")]
    [UnityEngine.RequireComponent(typeof(UnityEngine.AudioSource))]
    public class DOPitch : EasyDOTween.Animation<UnityEngine.AudioSource>
    {
        
        [UnityEngine.SerializeField()]
        private float endValue;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.AudioSource target, float duration)
        {
            return target.DOPitch(endValue, duration);
        }
    }
}

#endif