#if EasyDOTween_UI
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.Slider
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/Slider/DOValue")]
    [UnityEngine.RequireComponent(typeof(UnityEngine.UI.Slider))]
    public class DOValue : EasyDOTween.Animation<UnityEngine.UI.Slider>
    {
        
        [UnityEngine.SerializeField()]
        private float endValue;
        
        [UnityEngine.SerializeField()]
        private bool snapping = false;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.UI.Slider target, float duration)
        {
            return target.DOValue(endValue, duration, snapping);
        }
    }
}

#endif