//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.Transform
{
    using DG.Tweening;
    
    
    [UnityEngine.AddComponentMenu("EasyDOTween/Transform/DOLookAt")]
    public class DOLookAt : EasyDOTween.Animation<UnityEngine.Transform>
    {
        
        [UnityEngine.SerializeField()]
        private UnityEngine.Vector3 towards;
        
        [UnityEngine.SerializeField()]
        private DG.Tweening.AxisConstraint axisConstraint;
        
        [UnityEngine.SerializeField()]
        private System.Nullable<UnityEngine.Vector3> up;
        
        protected override DG.Tweening.Tween CreateTween(UnityEngine.Transform target, float duration)
        {
            return target.DOLookAt(towards, duration, axisConstraint, up);
        }
    }
}
